test:
  image: amazoncorretto:22-alpine
  script:
    - cd Spring
    - chmod +x gradlew
    - ./gradlew test


build:
  image: amazoncorretto:22-alpine-full
  script:
    - cd Spring
    - chmod +x gradlew
    - ./gradlew build -x test

install-docker:
  services:
    - docker:24.0.5-dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"
build-image:
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - cd Spring
    - docker buildx build -t trungtamthethao:latest .
    - docker push trungtamthethao:latest

pull-image:
  stage: deploy
  needs:
    - job: build-docker-image
      artifacts: false
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      sudo docker pull htilssu/trungtamthethao:latest &&
      sudo docker stop trungtamthethao &&
      sudo docker rm trungtamthethao &&
      sudo docker run -d --name trungtamthethao -p 8080:8080 htilssu/trungtamthethao:latest
      "
