name: Lint
on:
  - push
  - pull_request
permissions:
    contents: read
    statuses: write
    packages: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
