name: Lint
on:
  - push
  - pull_request

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
permissions:
  contents: read
  statuses: write
  packages: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: 'true'
